apiVersion: apps/v1
kind: Deployment
metadata:
 name: mohi-node-deployment
 namespace: node
 labels:
   app: node
spec:
 replicas: 3
 selector:
   matchLabels:
     app: node
 template:
   metadata:
     labels:
       app: node
   spec:
     containers:
     - name: mohi-node
       image: auwalu5/mohi-nodejs-app
       ports:
       - containerPort: 3000
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1

---

apiVersion: v1
kind: Service
metadata:
  name: mohi-node-service
  namespace: node
spec:
  selector:
    app: node
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 3000
    targetPort: 3000
      
      

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mohi-node-ingress
  namespace: node
spec:
  ingressClassName: ingress-controller
  rules:
  - host: "node.mdeey.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mohi-node-service
            port:
              number: 3000